// Curated snapshot checked on 2026-09-09 (JST).
// "Free" means a provider free plan/offer or an OpenRouter :free endpoint.
// Availability and rate limits can change; the server still validates every
// provider/model pair against this allowlist before forwarding a request.

export const PROVIDERS = Object.freeze({
  groq: Object.freeze({
    id: "groq",
    label: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    keyEnv: "GROQ_API_KEY",
    supportsReasoning: false,
    freeLabel: "Free plan枠",
    docsUrl: "https://console.groq.com/docs/rate-limits",
  }),
  bai: Object.freeze({
    id: "bai",
    label: "B.AI",
    baseUrl: "https://api.b.ai/v1",
    keyEnv: "BAI_API_KEY",
    freeLabel: "API 0 Credits",
    docsUrl: "https://docs.b.ai/llmservice/promotions-and-pricing-notices/",
  }),
  experientiallabs: Object.freeze({
    id: "experientiallabs",
    label: "Experiential Labs",
    baseUrl: "https://api.experientiallabs.ai/v1",
    keyEnv: "EXPERIENTIAL_LABS_API_KEY",
    supportsReasoning: true,
    reasoningParameter: "reasoning_effort",
    defaultReasoningEffort: "high",
    freeLabel: "FREE",
    docsUrl: "https://platform.experientiallabs.ai/models",
  }),
  openrouter: Object.freeze({
    id: "openrouter",
    label: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    keyEnv: "OPENROUTER_API_KEY",
    freeLabel: ":free endpoint",
    docsUrl: "https://openrouter.ai/docs/guides/routing/model-variants/free",
  }),
});

function model(provider, id, name, options = {}) {
  return Object.freeze({
    key: `${provider}:${id}`,
    provider,
    id,
    name,
    vision: Boolean(options.vision),
    inputModalities: options.inputModalities || (options.vision ? ["text", "image"] : ["text"]),
    outputModalities: options.outputModalities || ["text"],
    supportsTools: options.supportsTools !== false,
    supportsReasoning: options.supportsReasoning !== false,
    supportsTemperature: options.supportsTemperature !== false,
    freeLabel: options.freeLabel || PROVIDERS[provider].freeLabel,
    note: options.note || "",
  });
}

// Experiential Labs public catalog snapshot checked on 2026-09-09 (JST).
// Each row has: slug, display name, image input, tools, reasoning, temperature.
// The list is limited to active host-managed routes that do not require payment
// and return text, so image/output-only endpoints are not offered by this chat UI.
const EXPERIENTIAL_FREE_MODELS = Object.freeze([
  ["claude-fable-5.1","Claude Fable 5.1",true,true,true,true],
  ["claude-fable-5","Claude Fable 5",true,true,true,true],
  ["claude-opus-5","Claude Opus 5",true,true,true,true],
  ["claude-sonnet-5","Claude Sonnet 5",true,true,true,true],
  ["gpt-5.6-sol","GPT-5.6 Sol",true,true,true,true],
  ["gpt-5.6-luna","GPT-5.6 Luna",true,true,true,true],
  ["gemini-3.7-flash","Gemini 3.7 Flash",true,true,true,true],
  ["kimi-k3","Kimi K3",true,true,false,true],
  ["glm-5.3","GLM 5.3",false,true,true,true],
  ["glm-5.3-flash","GLM-5.3 Flash",true,true,true,true],
  ["deepseek-v4-flash","DeepSeek V4 Flash",false,true,false,true],
  ["qwen3.8-27b","Qwen3.8 27B",true,true,true,true],
  ["claude-fable-5-batch","Claude Fable 5 (batch)",true,true,true,true],
  ["claude-fable-latest","Claude Fable Latest",true,true,true,true],
  ["claude-haiku-4.5","Claude Haiku 4.5",true,true,true,true],
  ["claude-haiku-4.5-batch","Claude Haiku 4.5 Batch",true,true,true,true],
  ["claude-opus-4.5","Claude Opus 4.5",true,true,false,true],
  ["claude-opus-4.5-batch","Claude Opus 4.5 Batch",true,true,false,true],
  ["claude-opus-4.6","Claude Opus 4.6",true,true,true,true],
  ["claude-opus-4.6-batch","Claude Opus 4.6 Batch",true,true,true,true],
  ["claude-opus-4.7","Claude Opus 4.7",true,true,true,true],
  ["claude-opus-4.7-batch","Claude Opus 4.7 (batch)",true,true,true,true],
  ["claude-opus-4.8","Claude Opus 4.8",true,true,true,true],
  ["claude-opus-4.8-batch","Claude Opus 4.8 (batch)",true,true,true,true],
  ["claude-opus-5-batch","Claude Opus 5 (batch)",true,true,true,true],
  ["claude-opus-latest","Claude Opus Latest",true,true,true,true],
  ["claude-sonnet-4.5","Claude Sonnet 4.5",true,true,false,true],
  ["claude-sonnet-4.5-batch","Claude Sonnet 4.5 (Batch)",true,true,false,true],
  ["claude-sonnet-4.6","Claude Sonnet 4.6",true,true,true,true],
  ["claude-sonnet-4.6-batch","Claude Sonnet 4.6 Batch",true,true,true,true],
  ["claude-sonnet-5-batch","Claude Sonnet 5 (batch)",true,true,true,true],
  ["claude-sonnet-latest","Claude Sonnet Latest",true,true,true,true],
  ["codestral-2508","Codestral 2508",false,true,false,true],
  ["command-a","Command A",false,true,false,true],
  ["command-r-08-2024","Command R (08-2024)",false,true,false,true],
  ["command-r7b-12-2024","Command R7B (12-2024)",false,false,false,true],
  ["cydonia-24b-v4.1","Cydonia 24B V4.1",false,false,false,true],
  ["deepseek-r1","Deepseek R1",false,false,false,true],
  ["deepseek-v3.1","DeepSeek V3.1",false,true,false,true],
  ["deepseek-v3.2","DeepSeek V3.2",false,true,false,true],
  ["deepseek-v3.2-exp","DeepSeek V3.2 Exp",false,true,true,true],
  ["deepseek-v3.2-speciale","Deepseek V3.2 Speciale",false,false,false,true],
  ["deepseek-v4-flash-0731","DeepSeek V4 Flash 0731",false,true,false,true],
  ["deepseek-v4-flash-latest","DeepSeek V4 Flash Latest",false,true,true,true],
  ["deepseek-v4-flash-vision-exp","DeepSeek V4 Flash Vision Exp",true,true,false,true],
  ["deepseek-v4-pro","DeepSeek V4 Pro",false,true,false,true],
  ["deepseek-v4-pro-0813","DeepSeek V4 Pro 0813",false,true,false,true],
  ["devstral-2-123b","Devstral 2 123B",false,true,false,true],
  ["dolphin-mistral-24b-venice-edition","Dolphin Mistral 24B Venice Edition",false,false,false,true],
  ["gemini-2.5-flash-lite","Gemini 2.5 Flash Lite",true,true,true,true],
  ["gemini-3-flash-preview","Gemini 3 Flash Preview",true,true,true,true],
  ["gemini-3.1-flash-lite","Gemini 3.1 Flash Lite",true,true,true,true],
  ["gemini-3.1-pro-preview","Gemini 3.1 Pro Preview",true,true,true,true],
  ["gemini-3.1-pro-preview-customtools","Gemini 3.1 Pro Preview Custom Tools",true,true,true,true],
  ["gemini-3.5-flash","Gemini 3.5 Flash",true,true,true,true],
  ["gemini-3.5-flash-lite","Gemini 3.5 Flash Lite",true,true,true,true],
  ["gemini-3.6-flash","Gemini 3.6 Flash",true,true,true,true],
  ["gemini-3.8-flash","Gemini 3.8 Flash",true,true,true,true],
  ["gemini-flash-latest","Gemini Flash Latest",true,true,false,true],
  ["gemini-pro-latest","Gemini Pro Latest",true,true,false,true],
  ["gemma-3-12b-it","Gemma 3 12B IT",true,true,false,true],
  ["gemma-3-27b-it","Gemma 3 27B PT",true,true,false,true],
  ["gemma-3-4b-it","Gemma 3 4B IT",true,true,false,true],
  ["gemma-4-26b-a4b-it","Fw Gemma 4 26b A4b It",false,true,false,true],
  ["gemma-4-26b-a4b-it-free","Gemma 4 26B A4B IT (free)",true,true,true,true],
  ["gemma-4-31b","Gemma 4 31B",false,false,false,true],
  ["glm-4-32b-0414-128k","GLM-4-32B-0414-128K",false,true,false,true],
  ["glm-4.5","GLM 4.5",false,true,false,true],
  ["glm-4.5-air","GLM 4.5 Air",false,true,false,true],
  ["glm-4.5-airx","GLM 4.5 AirX",false,true,false,true],
  ["glm-4.5-flash","GLM 4.5 Flash",false,true,false,true],
  ["glm-4.5-x","GLM 4.5-X",false,true,false,true],
  ["glm-4.5v","GLM 4.5V",true,true,false,true],
  ["glm-4.6","GLM 4.6",false,true,false,true],
  ["glm-4.6v-flash","GLM 4.6V Flash",true,true,false,true],
  ["glm-4.6v-flashx","GLM 4.6V FlashX",true,true,false,true],
  ["glm-4.7","GLM 4.7",false,true,false,true],
  ["glm-4.7-flash","GLM 4.7 Flash",false,true,false,true],
  ["glm-4.7-flashx","GLM 4.7 FlashX",false,true,false,true],
  ["glm-5","GLM 5",false,true,false,true],
  ["glm-5-turbo","GLM 5 Turbo",false,true,false,true],
  ["glm-5.1","GLM 5.1",false,true,false,true],
  ["glm-5.2","GLM 5.2",false,true,false,true],
  ["glm-5v-turbo","GLM 5V Turbo",true,true,false,true],
  ["gpt-4.1","GPT-4.1",false,true,false,true],
  ["gpt-4.1-mini","GPT-4.1 Mini",false,true,false,true],
  ["gpt-4.1-nano","GPT-4.1 Nano",false,true,false,true],
  ["gpt-4o","GPT-4o",false,true,false,true],
  ["gpt-4o-mini","GPT-4o Mini",false,true,false,true],
  ["gpt-5","GPT-5",false,true,true,false],
  ["gpt-5-mini","GPT-5 Mini",false,true,true,false],
  ["gpt-5-nano","GPT-5 Nano",false,true,true,false],
  ["gpt-5.1","GPT-5.1",false,true,true,true],
  ["gpt-5.2","GPT-5.2",false,true,true,true],
  ["gpt-5.4","GPT-5.4",true,true,true,true],
  ["gpt-5.4-batch","GPT-5.4 Batch",true,true,true,true],
  ["gpt-5.4-mini","GPT-5.4 Mini",false,true,true,true],
  ["gpt-5.4-nano","GPT-5.4 Nano",false,true,true,true],
  ["gpt-5.5","GPT-5.5",true,true,true,true],
  ["gpt-5.5-batch","GPT-5.5 (batch)",true,true,true,true],
  ["gpt-5.5-pro","GPT-5.5 Pro",true,true,true,false],
  ["gpt-5.5-pro-batch","GPT-5.5 Pro (batch)",true,true,true,false],
  ["gpt-5.6-luna-batch","GPT-5.6 Luna (batch)",true,true,true,true],
  ["gpt-5.6-sol-batch","GPT-5.6 Sol (batch)",true,true,true,true],
  ["gpt-5.6-terra","GPT-5.6 Terra",true,true,true,true],
  ["gpt-5.6-terra-batch","GPT-5.6 Terra (batch)",true,true,true,true],
  ["gpt-6-astra","GPT-6 Astra",true,true,true,false],
  ["gpt-chat-latest","GPT Chat Latest",true,true,false,false],
  ["gpt-oss-120b","GPT Oss 120b",false,true,false,true],
  ["gpt-oss-20b","GPT Oss 20b",false,true,false,true],
  ["gpt-oss-safeguard-120b","Gpt Oss Safeguard 120b",false,true,false,true],
  ["gpt-oss-safeguard-20b","Gpt Oss Safeguard 20b",false,true,false,true],
  ["granite-4.0-h-micro","Granite 4.0 Micro",false,false,false,true],
  ["grok-4","Grok 4",false,true,false,true],
  ["grok-4-1-fast-non-reasoning","Grok 4 1 Fast Non Reasoning",false,true,false,true],
  ["grok-4-1-fast-reasoning","Grok 4 1 Fast Reasoning",false,true,false,true],
  ["grok-4.20","Grok 4.20",true,true,false,true],
  ["grok-4.20-multi-agent","Grok 4.20 Multi-Agent",true,true,false,true],
  ["grok-4.20-non-reasoning","Grok 4.20 Non-Reasoning",true,true,false,true],
  ["grok-4.3","Grok 4.3",true,true,true,true],
  ["grok-4.5","Grok 4.5",true,false,true,true],
  ["grok-4.6","Grok 4.6",true,true,true,true],
  ["grok-build-0.1","Grok Build 0.1",true,false,false,true],
  ["grok-code-fast-1","Grok Code Fast 1",false,true,false,true],
  ["hunyuan-a13b-instruct","Hunyuan A13B Instruct",false,false,true,true],
  ["hy-mt2-1.8b","Hy-MT2-1.8B",false,false,false,true],
  ["hy-mt2-30b-a3b","Hy-MT2-30B-A3B",false,false,false,true],
  ["hy-mt2-7b","Hy-MT2-7B",false,false,false,true],
  ["hy3","Hy3",false,true,false,true],
  ["hy3-preview","Hy3 Preview",false,true,true,true],
  ["hy4-preview","Tencent Hy4 Preview",false,true,true,true],
  ["inkling","Inkling",true,true,false,true],
  ["kimi-k2-thinking","Fw Kimi K2 Thinking",false,true,false,true],
  ["kimi-k2.5","Kimi K2.5",true,true,false,true],
  ["kimi-k2.6","Kimi K2.6",true,true,false,true],
  ["kimi-k2.7-code","Kimi K2.7 Code",true,true,false,true],
  ["laguna-s-2.1","Laguna S 2.1",false,true,true,true],
  ["laguna-s-2.1-free","Laguna S 2.1 (free)",false,true,true,true],
  ["laguna-xs-2.1","Laguna XS 2.1",false,true,true,true],
  ["laguna-xs-2.1-free","Laguna XS 2.1 (free)",false,true,true,true],
  ["lfm-2.5-2.6b-free","LFM2.5-2.6B (free)",false,true,true,true],
  ["ling-3.0-flash","Ling 3.0 Flash",false,true,true,true],
  ["ling-3.0-flash-fin","Ling 3.0 Flash Fin",false,true,true,true],
  ["ling-3.0-flash-fin-free","Ling 3.0 Flash Fin (Free)",false,true,true,true],
  ["llama-3-lunaris-8b","Llama 3 Lunaris 8B",false,false,false,true],
  ["llama-3.1-70b-instruct","Llama 3.1 70B Instruct",false,false,false,true],
  ["llama-4-maverick","Llama 4 Maverick",true,true,false,true],
  ["llama-4-scout","Llama 4 Scout",true,false,false,true],
  ["llama-guard-4-12b","Llama Guard 4 12B",true,false,false,true],
  ["magistral-small-2509","Magistral Small 2509",true,false,false,true],
  ["mercury-2","Mercury 2",false,true,true,true],
]);

const EXPERIENTIAL_MODEL_CATALOG = EXPERIENTIAL_FREE_MODELS.map(
  ([id, name, vision, supportsTools, supportsReasoning, supportsTemperature]) =>
    model("experientiallabs", id, name, {
      vision,
      supportsTools,
      supportsReasoning,
      supportsTemperature,
      freeLabel: "FREE",
      note: "Experiential Labsの無料アクセス枠（利用上限・提供条件は変動）",
    }),
);

export const MODEL_CATALOG = Object.freeze([
  // Groq Free Plan Limits: chat-capable models from the current catalog.
  model("groq", "openai/gpt-oss-120b", "GPT OSS 120B"),
  model("groq", "openai/gpt-oss-20b", "GPT OSS 20B"),
  model("groq", "openai/gpt-oss-safeguard-20b", "GPT OSS Safeguard 20B", { supportsTools: false }),
  model("groq", "qwen/qwen3.6-27b", "Qwen3.6 27B", { vision: true }),
  model("groq", "qwen/qwen3.8-27b", "Qwen3.8 27B", { vision: true }),
  model("groq", "groq/compound", "Groq Compound"),
  model("groq", "groq/compound-mini", "Groq Compound Mini"),

  // B.AI's current 0-Credit API offers.
  model("bai", "glm-5.3-flash", "GLM-5.3 Flash", { vision: true }),
  model("bai", "qwen3.8-flash", "Qwen3.8 Flash", { vision: true }),
  model("bai", "mimo-v2.5", "MiMo-V2.5", { vision: true }),

  // Experiential Labs FREE catalog snapshot (151 text-chat models).
  ...EXPERIENTIAL_MODEL_CATALOG,

  // OpenRouter Models API snapshot (2026-09-09): zero-priced text-chat endpoints.
  model("openrouter", "nvidia/nemotron-3-ultra-550b-a55b:free", "NVIDIA Nemotron 3 Ultra", { supportsTools: true }),
  model("openrouter", "openrouter/free", "Free Models Router", { vision: true }),
  model("openrouter", "inclusionai/ling-3.0-flash-sante:free", "Ling 3.0 Flash Sante", { supportsTools: true }),
  model("openrouter", "inclusionai/ling-3.0-flash-fin:free", "Ling 3.0 Flash Fin", { supportsTools: true }),
  model("openrouter", "dots-studio/dots-3-note-preview:free", "Dots3 Note Preview", { vision: true }),
  model("openrouter", "liquid/lfm-2.5-2.6b:free", "LFM2.5 2.6B"),
  model("openrouter", "nvidia/nemotron-3.5-lightning:free", "NVIDIA Nemotron 3.5 Lightning"),
  model("openrouter", "thinkingmachines/inkling-small:free", "Inkling Small", { vision: true }),
  model("openrouter", "poolside/laguna-s-2.1:free", "Laguna S 2.1"),
  model("openrouter", "thinkingmachines/inkling:free", "Inkling", { vision: true }),
  model("openrouter", "poolside/laguna-xs-2.1:free", "Laguna XS 2.1"),
  model("openrouter", "cohere/north-mini-code:free", "Cohere North Mini Code"),
  model("openrouter", "nvidia/nemotron-3.5-content-safety:free", "NVIDIA Nemotron 3.5 Content Safety", { vision: true, supportsTools: false }),
  model("openrouter", "nex-agi/nex-n2.5-mini:free", "Nex AGI Nex-N2.5 Mini"),
  model("openrouter", "nex-agi/nex-n2.5-pro:free", "Nex AGI Nex-N2.5 Pro", { vision: true }),
  model("openrouter", "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", "NVIDIA Nemotron 3 Nano Omni", { vision: true }),
  model("openrouter", "google/gemma-4-26b-a4b-it:free", "Gemma 4 26B", { vision: true }),
  model("openrouter", "google/gemma-4-31b-it:free", "Gemma 4 31B", { vision: true }),
  model("openrouter", "nvidia/nemotron-3-super-120b-a12b:free", "NVIDIA Nemotron 3 Super"),
]);

export const DEFAULT_MODEL = MODEL_CATALOG.find(
  (entry) => entry.provider === "openrouter" && entry.id === "nvidia/nemotron-3-ultra-550b-a55b:free",
);
export const DEFAULT_MODEL_KEY = DEFAULT_MODEL.key;

export function findModel(providerId, modelId) {
  return MODEL_CATALOG.find((entry) => entry.provider === providerId && entry.id === modelId) || null;
}

export function providerFor(providerId) {
  return PROVIDERS[providerId] || null;
}
